import type { Brand, Drink } from './types.ts';
import { ICE, vals } from './shared.ts';

/**
 * Adult beverages. Two things make this category different from coffee:
 *
 *  1. Preference is as much about *flavour direction* (dry vs sweet, how bitter,
 *     how boozy) as it is about a named drink, so those axes are first-class.
 *  2. Zero-proof matters. Every profile can flag "I'm not drinking", and each
 *     spirit family carries a non-alcoholic counterpart, so a host can pour
 *     something thoughtful rather than handing over a soda water.
 */
export const bar: Brand = {
  id: 'bar',
  name: 'Bar & adult beverages',
  short: 'Bar',
  emoji: '🍸',
  hue: 340,
  blurb: 'Cocktails, wine, beer and spirits — with the zero-proof version of each.',
  sources: [
    'https://www.thecocktailproject.com/cocktail-flavor-profiles',
    'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7466201/',
  ],
  groups: [
    {
      id: 'abv',
      label: 'Alcohol',
      kind: 'single',
      hint: 'Set this first — it is the part peers most need to get right.',
      values: vals(
        { id: 'full', label: 'Full strength', tags: ['alcohol'] },
        { id: 'low-abv', label: 'Low ABV / session strength', tags: ['alcohol'] },
        { id: 'zero-proof', label: 'Zero proof — make it the NA version', tags: ['zero-proof'] },
        { id: 'never', label: 'I do not drink alcohol', note: 'Peers will only ever see zero-proof suggestions', tags: ['zero-proof'] },
      ),
      fallback: 'full',
    },
    {
      id: 'spirit',
      label: 'Spirit',
      kind: 'single',
      values: vals(
        { id: 'none', label: 'No spirit' },
        { id: 'vodka', label: 'Vodka', tags: ['alcohol'] },
        { id: 'gin', label: 'Gin', tags: ['alcohol'] },
        { id: 'london-dry', label: 'Gin — London Dry', tags: ['alcohol'] },
        { id: 'old-tom', label: 'Gin — Old Tom', tags: ['alcohol'] },
        { id: 'blanco-tequila', label: 'Tequila — Blanco', tags: ['alcohol'] },
        { id: 'reposado', label: 'Tequila — Reposado', tags: ['alcohol'] },
        { id: 'anejo', label: 'Tequila — Añejo', tags: ['alcohol'] },
        { id: 'mezcal', label: 'Mezcal', tags: ['alcohol'] },
        { id: 'white-rum', label: 'Rum — White', tags: ['alcohol'] },
        { id: 'dark-rum', label: 'Rum — Dark / aged', tags: ['alcohol'] },
        { id: 'spiced-rum', label: 'Rum — Spiced', tags: ['alcohol'] },
        { id: 'rhum-agricole', label: 'Rhum agricole', tags: ['alcohol'] },
        { id: 'bourbon', label: 'Whiskey — Bourbon', tags: ['alcohol'] },
        { id: 'rye', label: 'Whiskey — Rye', tags: ['alcohol'] },
        { id: 'scotch-blend', label: 'Whisky — Blended Scotch', tags: ['alcohol'] },
        { id: 'single-malt', label: 'Whisky — Single malt', tags: ['alcohol'] },
        { id: 'peated', label: 'Whisky — Peated / Islay', tags: ['alcohol'] },
        { id: 'irish', label: 'Whiskey — Irish', tags: ['alcohol'] },
        { id: 'japanese', label: 'Whisky — Japanese', tags: ['alcohol'] },
        { id: 'cognac', label: 'Cognac / Brandy', tags: ['alcohol'] },
        { id: 'pisco', label: 'Pisco', tags: ['alcohol'] },
        { id: 'cachaca', label: 'Cachaça', tags: ['alcohol'] },
        { id: 'aperitivo', label: 'Aperitivo (Aperol, Campari)', tags: ['alcohol'] },
        { id: 'amaro', label: 'Amaro', tags: ['alcohol'] },
        { id: 'vermouth', label: 'Vermouth', tags: ['alcohol'] },
        { id: 'sake', label: 'Sake', tags: ['alcohol'] },
        { id: 'soju', label: 'Soju', tags: ['alcohol'] },
        { id: 'na-spirit', label: 'Non-alcoholic spirit', note: 'Seedlip, Ritual, Lyre’s and friends', tags: ['zero-proof'] },
      ),
      fallback: 'none',
    },
    {
      id: 'flavor_profile',
      label: 'Flavour direction',
      kind: 'multi',
      hint: 'The most useful thing to share — it lets someone pick for you.',
      values: vals(
        'Dry',
        'Sweet',
        'Sour / citrus-forward',
        'Bitter',
        'Herbal',
        'Smoky',
        'Spicy',
        'Fruity',
        'Floral',
        'Savoury / umami',
        'Creamy',
        'Refreshing & long',
        'Spirit-forward & short',
      ),
    },
    {
      id: 'sweetness_level',
      label: 'How sweet',
      kind: 'scale',
      values: vals('Bone dry', 'Dry', 'Off-dry', 'Balanced', 'Sweet', 'Dessert sweet'),
      fallback: 'balanced',
    },
    {
      id: 'strength',
      label: 'How strong',
      kind: 'scale',
      values: vals('Barely there', 'Easy', 'Standard pour', 'Stiff', 'Make it count'),
      fallback: 'standard-pour',
    },
    {
      id: 'serve',
      label: 'Serve',
      kind: 'single',
      values: vals('Neat', 'On the rocks', 'Up / chilled, no ice', 'Tall with mixer', 'Frozen / blended', 'Hot'),
      fallback: 'on-the-rocks',
    },
    {
      id: 'ice_style',
      label: 'Ice style',
      kind: 'single',
      advanced: true,
      values: vals('No preference', 'Big rock', 'Cubes', 'Crushed / pebble', 'Neat, no ice'),
      fallback: 'no-preference',
    },
    {
      id: 'mixer',
      label: 'Mixer',
      kind: 'multi',
      values: vals(
        'Soda water',
        'Tonic',
        'Diet tonic',
        'Ginger beer',
        'Ginger ale',
        'Cola',
        'Diet cola',
        'Lemon-lime soda',
        'Grapefruit soda',
        'Cranberry juice',
        'Orange juice',
        'Pineapple juice',
        'Tomato / Clamato',
        'Lemonade',
        'Iced tea',
        'Coconut water',
        'Espresso',
        'No mixer',
      ),
    },
    {
      id: 'garnish',
      label: 'Garnish',
      kind: 'multi',
      values: vals(
        'Lime wedge',
        'Lemon twist',
        'Orange peel',
        'Olives',
        'Extra olives',
        'Cocktail onion',
        'Cherry',
        'Mint sprig',
        'Cucumber',
        'Salt rim',
        'Tajín / chili rim',
        'Sugar rim',
        'No garnish',
      ),
    },
    {
      id: 'wine_style',
      label: 'Wine style',
      kind: 'multi',
      values: vals(
        'Red — light (Pinot Noir, Gamay)',
        'Red — medium (Merlot, Sangiovese)',
        'Red — full (Cabernet, Malbec, Syrah)',
        'White — crisp (Sauvignon Blanc, Pinot Grigio)',
        'White — rich (Chardonnay, white Rhône)',
        'White — aromatic (Riesling, Gewürztraminer)',
        'Rosé',
        'Orange / skin contact',
        'Sparkling — Champagne / traditional method',
        'Sparkling — Prosecco',
        'Sparkling — Cava',
        'Pét-nat',
        'Dessert wine',
        'Fortified (Port, Sherry, Madeira)',
        'Non-alcoholic wine',
      ),
    },
    {
      id: 'beer_style',
      label: 'Beer style',
      kind: 'multi',
      values: vals(
        'Light lager',
        'Pilsner',
        'Helles / Munich lager',
        'Amber / Vienna lager',
        'Pale ale',
        'IPA — West Coast',
        'IPA — Hazy / New England',
        'Double IPA',
        'Session IPA',
        'Wheat / Hefeweizen',
        'Witbier',
        'Belgian ale',
        'Saison',
        'Sour / gose',
        'Fruited sour',
        'Porter',
        'Stout',
        'Nitro stout',
        'Imperial stout',
        'Brown ale',
        'Cider',
        'Hard seltzer',
        'Non-alcoholic beer',
      ),
    },
    {
      id: 'hard_no',
      label: 'Hard no',
      kind: 'multi',
      hint: 'What should never end up in front of you.',
      values: vals(
        'Anything with gin',
        'Anything with tequila',
        'Anything with whiskey',
        'Anything peated / smoky',
        'Anything with anise or licorice',
        'Anything with egg white',
        'Anything with dairy',
        'Anything with coconut',
        'Anything overly sweet',
        'Anything with an energy drink',
        'Shots',
        'Nothing is off limits',
      ),
    },
    {
      id: 'occasion_note',
      label: 'House rule',
      kind: 'single',
      advanced: true,
      values: vals(
        'No limits worth mentioning',
        'One drink and I switch to water',
        'Two-drink maximum',
        'Only on weekends',
        'Only with food',
        'Never when I am driving — assume NA',
      ),
      fallback: 'no-limits-worth-mentioning',
    },
  ],
  drinks: [
    // Cocktails
    b('old-fashioned', 'Old Fashioned', 'Cocktail'),
    b('manhattan', 'Manhattan', 'Cocktail'),
    b('negroni', 'Negroni', 'Cocktail'),
    b('boulevardier', 'Boulevardier', 'Cocktail'),
    b('martini', 'Martini', 'Cocktail'),
    b('dirty-martini', 'Dirty Martini', 'Cocktail'),
    b('espresso-martini', 'Espresso Martini', 'Cocktail'),
    b('margarita', 'Margarita', 'Cocktail'),
    b('spicy-margarita', 'Spicy Margarita', 'Cocktail'),
    b('paloma', 'Paloma', 'Cocktail'),
    b('daiquiri', 'Daiquiri', 'Cocktail'),
    b('mojito', 'Mojito', 'Cocktail'),
    b('whiskey-sour', 'Whiskey Sour', 'Cocktail'),
    b('gin-tonic', 'Gin & Tonic', 'Highball'),
    b('vodka-soda', 'Vodka Soda', 'Highball'),
    b('moscow-mule', 'Moscow Mule', 'Highball'),
    b('dark-and-stormy', 'Dark & Stormy', 'Highball'),
    b('aperol-spritz', 'Aperol Spritz', 'Spritz'),
    b('hugo-spritz', 'Hugo Spritz', 'Spritz'),
    b('americano-cocktail', 'Americano', 'Spritz'),
    b('french-75', 'French 75', 'Cocktail'),
    b('cosmopolitan', 'Cosmopolitan', 'Cocktail'),
    b('bloody-mary', 'Bloody Mary', 'Brunch', ['day']),
    b('mimosa', 'Mimosa', 'Brunch', ['day']),
    b('michelada', 'Michelada', 'Brunch', ['day']),
    b('pina-colada', 'Piña Colada', 'Tiki'),
    b('mai-tai', 'Mai Tai', 'Tiki'),
    b('painkiller', 'Painkiller', 'Tiki'),
    b('irish-coffee', 'Irish Coffee', 'Warm'),
    b('hot-toddy', 'Hot Toddy', 'Warm'),
    b('mulled-wine', 'Mulled Wine', 'Warm'),
    // By the glass
    b('glass-of-wine', 'Glass of wine', 'Wine'),
    b('bottle-of-wine', 'Bottle of wine', 'Wine'),
    b('champagne', 'Champagne / sparkling', 'Wine'),
    b('beer-draft', 'Beer — draft', 'Beer'),
    b('beer-bottle', 'Beer — bottle or can', 'Beer'),
    b('cider', 'Cider', 'Beer'),
    b('hard-seltzer', 'Hard seltzer', 'Beer'),
    b('spirit-neat', 'Spirit, neat or rocks', 'Spirits'),
    b('shot', 'Shot', 'Spirits'),
    b('sake-serve', 'Sake', 'Spirits'),
    // Zero proof
    b('na-beer', 'Non-alcoholic beer', 'Zero proof'),
    b('na-wine', 'Non-alcoholic wine', 'Zero proof'),
    b('mocktail', 'Mocktail — bartender’s choice', 'Zero proof'),
    b('virgin-margarita', 'Zero-proof Margarita', 'Zero proof'),
    b('shirley-temple', 'Shirley Temple', 'Zero proof'),
    b('na-spritz', 'Zero-proof Spritz', 'Zero proof'),
    b('sparkling-water-bar', 'Sparkling water with lime', 'Zero proof'),
  ],
};

function b(id: string, name: string, family: string, dayparts: Drink['dayparts'] = ['adult']): Drink {
  return {
    id,
    name,
    family,
    dayparts,
    groups: [
      'abv', 'spirit', 'flavor_profile', 'sweetness_level', 'strength', 'serve',
      'ice_style', 'mixer', 'garnish', 'wine_style', 'beer_style', 'hard_no', 'occasion_note', 'ice',
    ],
    tags: family === 'Zero proof' ? ['zero-proof'] : ['alcohol'],
  };
}

// Keep the shared ice group reachable from this brand's group list.
bar.groups.push({ ...ICE, advanced: true });
