import type { Brand, Drink } from './types.ts';
import { CAFFEINE, ICE, SWEETENER, SWEETENER_COUNT, milkGroup, vals } from './shared.ts';

/**
 * Home and hosting. This is the brand that matters most for family and
 * house-guest use: "what do I put in front of this person when they visit".
 */
export const home: Brand = {
  id: 'home',
  name: 'At home & hosting',
  short: 'Home',
  emoji: '🏠',
  hue: 200,
  blurb: 'What to pour when someone visits — including the mug and how you take it.',
  groups: [
    {
      id: 'vessel',
      label: 'Vessel',
      kind: 'single',
      values: vals('Any mug', 'My usual mug', 'Big mug', 'Small cup', 'Glass', 'Travel tumbler', 'Straight from the pot'),
      fallback: 'any-mug',
    },
    { id: 'temp', label: 'Temperature', kind: 'single', values: vals('Hot', 'Iced', 'Blended', 'Room temperature', 'Lukewarm'), fallback: 'hot' },
    {
      id: 'brew_method',
      label: 'How it is made',
      kind: 'single',
      values: vals(
        'Drip machine',
        'Pour over',
        'French press',
        'Aeropress',
        'Moka pot',
        'Espresso machine',
        'Nespresso pod',
        'Keurig pod',
        'Instant',
        'Cold brew from the fridge',
        'Kettle and a tea bag',
        'Loose leaf, steeped properly',
        'Whatever is easiest',
      ),
      fallback: 'whatever-is-easiest',
    },
    milkGroup(
      ['whole-milk', '2-milk', 'nonfat-milk', 'half-and-half', 'heavy-cream', 'cream', 'oat-milk', 'almond-milk', 'soy-milk', 'coconut-milk', 'lactose-free', 'no-milk', 'milk-on-side'],
      'whole-milk',
    ),
    {
      id: 'milk_amount',
      label: 'How much milk',
      kind: 'scale',
      values: vals('None', 'A splash', 'A little', 'Regular', 'Milky', 'Mostly milk'),
      fallback: 'regular',
    },
    CAFFEINE,
    SWEETENER,
    SWEETENER_COUNT,
    {
      id: 'steep',
      label: 'Steep time',
      kind: 'single',
      advanced: true,
      hint: 'Tea drinkers have strong opinions here and rarely get asked.',
      values: vals('Whatever', 'Weak — pull the bag early', 'Standard — 3 minutes', 'Strong — 5 minutes', 'Leave the bag in', 'Take the bag out and leave it on the saucer'),
      fallback: 'whatever',
    },
    {
      id: 'addition',
      label: 'Additions',
      kind: 'multi',
      values: vals(
        { id: 'lemon', label: 'Lemon' },
        { id: 'lime', label: 'Lime' },
        { id: 'honey', label: 'Honey', tags: ['sugar'] },
        { id: 'cinnamon', label: 'Cinnamon' },
        { id: 'nutmeg', label: 'Nutmeg' },
        { id: 'vanilla', label: 'Vanilla', tags: ['sugar'] },
        { id: 'mint', label: 'Fresh mint' },
        { id: 'ginger', label: 'Ginger' },
        { id: 'salt', label: 'Pinch of salt' },
        { id: 'whipped-cream', label: 'Whipped cream', tags: ['dairy'] },
        { id: 'marshmallows', label: 'Marshmallows', tags: ['sugar'] },
        { id: 'butter', label: 'Butter / MCT oil', tags: ['dairy'] },
        { id: 'protein-powder', label: 'Protein powder' },
        { id: 'collagen', label: 'Collagen' },
      ),
    },
    ICE,
    {
      id: 'stock',
      label: 'Keep this in stock for me',
      kind: 'single',
      advanced: true,
      hint: 'For people who host you often.',
      values: vals('Not necessary', 'Nice if you have it', 'Yes please — I will always want this'),
      fallback: 'not-necessary',
    },
  ],
  drinks: [
    h('coffee', 'Coffee', 'Coffee', ['morning', 'day']),
    h('decaf-coffee', 'Decaf coffee', 'Coffee', ['evening'], ['decaf']),
    h('espresso', 'Espresso', 'Coffee', ['morning', 'day']),
    h('latte', 'Latte', 'Coffee', ['morning', 'day']),
    h('cold-brew', 'Cold brew', 'Coffee', ['morning', 'day']),
    h('instant-coffee', 'Instant coffee', 'Coffee', ['morning', 'day']),
    h('black-tea', 'Black tea', 'Tea', ['morning', 'day']),
    h('green-tea', 'Green tea', 'Tea', ['morning', 'day']),
    h('herbal-tea', 'Herbal tea', 'Tea', ['evening'], ['decaf']),
    h('chamomile', 'Chamomile', 'Tea', ['evening'], ['decaf']),
    h('peppermint-tea', 'Peppermint tea', 'Tea', ['evening'], ['decaf']),
    h('chai', 'Chai', 'Tea', ['morning', 'day']),
    h('matcha', 'Matcha', 'Tea', ['morning', 'day']),
    h('hot-chocolate', 'Hot chocolate', 'Other', ['evening'], ['decaf']),
    h('water', 'Water', 'Water', ['morning', 'day', 'evening'], ['decaf']),
    h('sparkling-water', 'Sparkling water', 'Water', ['morning', 'day', 'evening'], ['decaf']),
    h('juice', 'Juice', 'Cold', ['morning', 'day'], ['decaf']),
    h('soda', 'Soda', 'Cold', ['day'], ['decaf']),
    h('diet-soda', 'Diet soda', 'Cold', ['day'], ['decaf', 'sugar-free']),
    h('milk', 'Milk', 'Cold', ['morning', 'evening'], ['dairy', 'decaf']),
    h('kombucha', 'Kombucha', 'Cold', ['day'], ['decaf']),
    h('electrolyte-drink', 'Electrolyte drink', 'Cold', ['morning', 'day'], ['decaf']),
    h('energy-drink', 'Energy drink', 'Energy', ['morning', 'day']),
    h('protein-shake', 'Protein shake', 'Other', ['morning', 'day'], ['decaf']),
    h('smoothie', 'Smoothie', 'Other', ['morning', 'day'], ['decaf']),
    h('warm-milk', 'Warm milk', 'Other', ['evening'], ['dairy', 'decaf']),
    h('golden-milk', 'Golden milk', 'Other', ['evening'], ['decaf']),
  ],
};

function h(id: string, name: string, family: string, dayparts: Drink['dayparts'], tags?: Drink['tags']): Drink {
  return {
    id,
    name,
    family,
    dayparts,
    groups: ['vessel', 'temp', 'brew_method', 'milk', 'milk_amount', 'caffeine', 'sweetener', 'sweetener_count', 'steep', 'addition', 'ice', 'stock'],
    tags,
  };
}
