import type { Brand, Drink } from './types.ts';
import { ICE, SWEETNESS, milkGroup, vals } from './shared.ts';

/**
 * Boba / bubble tea. Sweetness and ice are percentages here rather than words,
 * which is exactly the kind of precision a shared profile should carry — "50%
 * sugar, light ice, half portion of pearls" is unambiguous at any shop.
 */
export const teahouse: Brand = {
  id: 'teahouse',
  name: 'Boba & bubble tea',
  short: 'Boba',
  emoji: '🧋',
  hue: 300,
  blurb: 'Sugar and ice as percentages, toppings by the scoop. Works at any shop.',
  sources: ['https://www.1992sharetea.com/news/how-to-customize-your-bubble-tea-order-at-sharetea'],
  groups: [
    {
      id: 'shop',
      label: 'Shop',
      kind: 'single',
      advanced: true,
      values: vals('Any boba shop', 'Sharetea', 'Kung Fu Tea', 'Gong Cha', 'Chatime', 'CoCo Fresh', 'Tiger Sugar', 'Happy Lemon', 'Boba Guys', 'Ten Ren', 'The Alley', 'Yifang', 'Local shop'),
      fallback: 'any-boba-shop',
    },
    { id: 'size', label: 'Size', kind: 'single', values: vals('Small — 16 oz', 'Medium — 20 oz', 'Large — 24 oz'), fallback: 'medium-20-oz' },
    { id: 'temp', label: 'Temperature', kind: 'single', values: vals('Cold', 'Hot', 'Blended / slush'), fallback: 'cold' },
    {
      id: 'tea_base',
      label: 'Tea base',
      kind: 'single',
      values: vals(
        { id: 'black', label: 'Black tea', tags: ['caffeine'] },
        { id: 'green', label: 'Green tea', tags: ['caffeine'] },
        { id: 'oolong', label: 'Oolong tea', tags: ['caffeine'] },
        { id: 'jasmine-green', label: 'Jasmine green tea', tags: ['caffeine'] },
        { id: 'assam', label: 'Assam black tea', tags: ['caffeine'] },
        { id: 'earl-grey', label: 'Earl Grey', tags: ['caffeine'] },
        { id: 'matcha', label: 'Matcha', tags: ['caffeine'] },
        { id: 'hojicha', label: 'Hojicha', tags: ['caffeine'] },
        { id: 'thai-tea', label: 'Thai tea', tags: ['caffeine', 'sugar'] },
        { id: 'taro', label: 'Taro', tags: ['decaf', 'sugar'] },
        { id: 'no-tea', label: 'No tea — fruit or milk base only', tags: ['decaf'] },
      ),
      fallback: 'black',
    },
    milkGroup(['whole-milk', '2-milk', 'nonfat-milk', 'oat-milk', 'almond-milk', 'soy-milk', 'coconut-milk', 'no-milk'], 'whole-milk'),
    {
      id: 'creamer',
      label: 'Creamer style',
      kind: 'single',
      values: vals(
        { id: 'nondairy-creamer', label: 'House non-dairy creamer', note: 'The traditional powder — usually contains milk derivatives' },
        { id: 'fresh-milk', label: 'Fresh milk', tags: ['dairy'] },
        { id: 'condensed-milk', label: 'Condensed milk', tags: ['dairy', 'sugar'] },
        { id: 'cheese-foam', label: 'Cheese foam / milk cap', tags: ['dairy'] },
        { id: 'none', label: 'None' },
      ),
      fallback: 'fresh-milk',
    },
    SWEETNESS,
    {
      id: 'ice_pct',
      label: 'Ice level',
      kind: 'scale',
      values: vals('No ice', '25% — light ice', '50% — less ice', '75%', '100% — regular ice', 'Extra ice'),
      fallback: '100-regular-ice',
    },
    {
      id: 'toppings',
      label: 'Toppings',
      kind: 'multi',
      hint: 'Mix as many as you like — most shops charge per topping.',
      values: vals(
        { id: 'tapioca', label: 'Tapioca pearls (boba)', tags: ['sugar'] },
        { id: 'mini-pearls', label: 'Mini pearls', tags: ['sugar'] },
        { id: 'crystal-boba', label: 'Crystal boba / agar', tags: ['sugar'] },
        { id: 'popping-boba', label: 'Popping boba', tags: ['sugar'] },
        { id: 'grass-jelly', label: 'Grass jelly' },
        { id: 'lychee-jelly', label: 'Lychee jelly', tags: ['sugar'] },
        { id: 'coconut-jelly', label: 'Coconut jelly', tags: ['sugar'] },
        { id: 'aloe-vera', label: 'Aloe vera' },
        { id: 'red-bean', label: 'Red bean', tags: ['sugar'] },
        { id: 'pudding', label: 'Egg pudding', tags: ['dairy', 'sugar'] },
        { id: 'cheese-foam-top', label: 'Cheese foam', tags: ['dairy'] },
        { id: 'creama', label: 'Milk foam / creama', tags: ['dairy'] },
        { id: 'oreo-crumble', label: 'Oreo crumble', tags: ['gluten', 'sugar'] },
        { id: 'basil-seeds', label: 'Basil seeds' },
        { id: 'sago', label: 'Sago', tags: ['sugar'] },
        { id: 'no-toppings', label: 'No toppings' },
      ),
    },
    {
      id: 'topping_amount',
      label: 'Topping portion',
      kind: 'scale',
      advanced: true,
      values: vals('Half portion', 'Regular', 'Extra'),
      fallback: 'regular',
    },
    {
      id: 'extras',
      label: 'Extras',
      kind: 'multi',
      advanced: true,
      values: vals('Wide straw', 'Sealed lid, no straw', 'Shake it well', 'Toppings on the side', 'Warm pearls please'),
    },
  ],
  drinks: [
    tea('classic-milk-tea', 'Classic Milk Tea', 'Milk tea', ['day', 'evening']),
    tea('brown-sugar-milk-tea', 'Brown Sugar Milk Tea', 'Milk tea', ['day', 'evening']),
    tea('taro-milk-tea', 'Taro Milk Tea', 'Milk tea', ['day', 'evening']),
    tea('thai-milk-tea', 'Thai Milk Tea', 'Milk tea', ['day']),
    tea('matcha-milk-tea', 'Matcha Milk Tea', 'Milk tea', ['morning', 'day']),
    tea('hojicha-latte', 'Hojicha Latte', 'Milk tea', ['day', 'evening']),
    tea('jasmine-milk-tea', 'Jasmine Milk Tea', 'Milk tea', ['day']),
    tea('oolong-milk-tea', 'Oolong Milk Tea', 'Milk tea', ['day']),
    tea('wintermelon-milk-tea', 'Wintermelon Milk Tea', 'Milk tea', ['day']),
    tea('strawberry-fruit-tea', 'Strawberry Fruit Tea', 'Fruit tea', ['day']),
    tea('mango-green-tea', 'Mango Green Tea', 'Fruit tea', ['day']),
    tea('passionfruit-tea', 'Passionfruit Tea', 'Fruit tea', ['day']),
    tea('peach-oolong', 'Peach Oolong Tea', 'Fruit tea', ['day']),
    tea('lychee-tea', 'Lychee Tea', 'Fruit tea', ['day']),
    tea('winter-melon-lemonade', 'Wintermelon Lemonade', 'Fruit tea', ['day']),
    tea('honey-lemon-green', 'Honey Lemon Green Tea', 'Fruit tea', ['day']),
    tea('plain-black-tea', 'Plain Brewed Tea', 'Straight tea', ['morning', 'day']),
    tea('cheese-foam-oolong', 'Cheese Foam Oolong', 'Straight tea', ['day']),
    tea('slush', 'Fruit Slush', 'Blended', ['day']),
    tea('taro-slush', 'Taro Slush', 'Blended', ['day', 'evening']),
  ],
};

function tea(id: string, name: string, family: string, dayparts: Drink['dayparts']): Drink {
  return {
    id,
    name,
    family,
    dayparts,
    groups: ['shop', 'size', 'temp', 'tea_base', 'milk', 'creamer', 'sweetness', 'ice_pct', 'toppings', 'topping_amount', 'extras'],
  };
}

// ---------------------------------------------------------------------------
// Juice, smoothies and shakes
// ---------------------------------------------------------------------------

export const juiceBar: Brand = {
  id: 'juice-bar',
  name: 'Juice bar & smoothies',
  short: 'Juice bar',
  emoji: '🥤',
  hue: 130,
  blurb: 'Jamba, Smoothie King, Tropical Smoothie, or whatever the gym café blends.',
  groups: [
    {
      id: 'shop',
      label: 'Shop',
      kind: 'single',
      advanced: true,
      values: vals('Any juice bar', 'Jamba', 'Smoothie King', 'Tropical Smoothie Café', 'Clean Juice', 'Nekter', 'Planet Smoothie', 'Grocery store juice bar', 'Home blender'),
      fallback: 'any-juice-bar',
    },
    { id: 'size', label: 'Size', kind: 'single', values: vals('Small — 16 oz', 'Medium — 24 oz', 'Large — 32 oz'), fallback: 'medium-24-oz' },
    {
      id: 'base',
      label: 'Liquid base',
      kind: 'single',
      values: vals(
        { id: 'water', label: 'Water' },
        { id: 'coconut-water', label: 'Coconut water' },
        { id: 'apple-juice', label: 'Apple juice', tags: ['sugar'] },
        { id: 'orange-juice', label: 'Orange juice', tags: ['sugar'] },
        { id: 'almond-milk', label: 'Almond milk', tags: ['dairy-free', 'nut'] },
        { id: 'oat-milk', label: 'Oat milk', tags: ['dairy-free'] },
        { id: 'soy-milk', label: 'Soy milk', tags: ['dairy-free', 'soy'] },
        { id: 'dairy-milk', label: 'Dairy milk', tags: ['dairy'] },
        { id: 'greek-yogurt', label: 'Greek yogurt', tags: ['dairy'] },
        { id: 'sherbet', label: 'Sherbet', tags: ['sugar'] },
      ),
      fallback: 'water',
    },
    {
      id: 'boost',
      label: 'Boosts & add-ins',
      kind: 'multi',
      values: vals(
        'Whey protein',
        'Plant protein',
        'Collagen',
        'Peanut butter',
        'Almond butter',
        'Chia seeds',
        'Flax seeds',
        'Hemp seeds',
        'Spinach / kale',
        'Avocado',
        'Ginger',
        'Turmeric',
        'Matcha',
        'Espresso shot',
        'Spirulina',
        'Immunity / vitamin boost',
        'Energy boost',
        'Fiber boost',
        'Probiotics',
        'Oats',
      ),
    },
    {
      id: 'sweet',
      label: 'Sweetener',
      kind: 'multi',
      values: vals(
        { id: 'none', label: 'None', tags: ['sugar-free'] },
        { id: 'honey', label: 'Honey', tags: ['sugar'] },
        { id: 'agave', label: 'Agave', tags: ['sugar'] },
        { id: 'dates', label: 'Dates', tags: ['sugar'] },
        { id: 'turbinado', label: 'Raw sugar', tags: ['sugar'] },
        { id: 'stevia', label: 'Stevia', tags: ['sugar-free'] },
      ),
      fallback: ['none'],
    },
    {
      id: 'texture',
      label: 'Texture',
      kind: 'single',
      values: vals('Standard', 'Extra thick', 'Thinner / more liquid', 'Bowl with toppings', 'No ice, fruit only'),
      fallback: 'standard',
    },
    ICE,
    {
      id: 'omit',
      label: 'Leave out',
      kind: 'multi',
      advanced: true,
      values: vals('Banana', 'Dairy', 'Added sugar', 'Nuts', 'Seeds', 'Anything green'),
    },
  ],
  drinks: [
    jb('strawberry-banana', 'Strawberry Banana Smoothie', 'Smoothie', ['morning', 'day']),
    jb('mango-smoothie', 'Mango Smoothie', 'Smoothie', ['morning', 'day']),
    jb('green-smoothie', 'Green Smoothie', 'Smoothie', ['morning', 'day']),
    jb('protein-shake', 'Protein Shake', 'Smoothie', ['morning', 'day']),
    jb('acai-bowl', 'Açaí Bowl', 'Bowl', ['morning', 'day']),
    jb('pitaya-bowl', 'Pitaya Bowl', 'Bowl', ['morning', 'day']),
    jb('cold-pressed-green', 'Cold-Pressed Green Juice', 'Juice', ['morning', 'day']),
    jb('orange-juice', 'Fresh Orange Juice', 'Juice', ['morning']),
    jb('carrot-ginger', 'Carrot Ginger Juice', 'Juice', ['morning', 'day']),
    jb('beet-juice', 'Beet Juice', 'Juice', ['morning', 'day']),
    jb('wellness-shot', 'Ginger / Turmeric Wellness Shot', 'Shot', ['morning']),
    jb('lemonade', 'Fresh Lemonade', 'Juice', ['day']),
    jb('milkshake', 'Milkshake', 'Shake', ['day', 'evening']),
  ],
};

function jb(id: string, name: string, family: string, dayparts: Drink['dayparts']): Drink {
  return { id, name, family, dayparts, groups: ['shop', 'size', 'base', 'boost', 'sweet', 'texture', 'ice', 'omit'], tags: ['decaf'] };
}
